project:
  type: website

website:
  title: "Posit Team Tutorials"
  search: false
  favicon: "favicon.png"
  navbar:
    background: light
    title: false
    logo: images/logo-team-full-color.png
    logo-alt: The logo for Posit Team
    right:
      - href: index.qmd
        text: Home
      - href: https://posit.co/contact-posit/
        text: Contact Posit
        target: _blank

format:
  html:
    theme: styles.scss
    toc: true
    toc-location: left
    sidebar: false
    smooth-scroll: true
    grid:
      sidebar-width: 300px
      body-width: 775px
      gutter-width: 3rem

editor: visual

